#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#    May 20, 2019 10:38:27 PM IST  platform: Windows NT

import sys
import tkinter.messagebox as tm
import os

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import create_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    create_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    create_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("832x579+263+62")
        top.title("Create")
        top.configure(background="#bfeaef")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.024, rely=0.035, relheight=0.927
                , relwidth=0.487)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#CAFAFE")
        self.Frame1.configure(highlightcolor="#646464")
        self.Frame1.configure(width=405)

        self.Label1 = tk.Label(self.Frame1)
        self.Label1.place(relx=0.198, rely=0.019, height=31, width=244)
        self.Label1.configure(background="#CAFAFE")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Castellar} -size 12 -weight bold -underline 1")
        self.Label1.configure(foreground="#296b5d")
        self.Label1.configure(highlightcolor="#646464")
        self.Label1.configure(text='''Student Details''')
        self.Label1.configure(width=244)

        self.Label2 = tk.Label(self.Frame1)
        self.Label2.place(relx=0.074, rely=0.15, height=21, width=64)
        self.Label2.configure(background="#CAFAFE")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font="-family {Consolas} -size 11 -weight bold -slant italic")
        self.Label2.configure(foreground="#379683")
        self.Label2.configure(text='''USN:''')
        self.Label2.configure(width=64)

        self.Entry1 = tk.Entry(self.Frame1)
        self.Entry1.place(relx=0.37, rely=0.15,height=19, relwidth=0.43)
        self.Entry1.configure(background="#e0ffff")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="-family {Consolas} -size 10 -slant italic")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(width=174)

        self.Label3 = tk.Label(self.Frame1)
        self.Label3.place(relx=0.074, rely=0.262, height=21, width=74)
        self.Label3.configure(background="#CAFAFE")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(font="-family {Consolas} -size 12 -weight bold -slant italic")
        self.Label3.configure(foreground="#379683")
        self.Label3.configure(text='''Name:''')
        self.Label3.configure(width=74)

        self.Entry2 = tk.Entry(self.Frame1)
        self.Entry2.place(relx=0.37, rely=0.262,height=20, relwidth=0.43)
        self.Entry2.configure(background="#e0ffff")
        self.Entry2.configure(disabledforeground="#a3a3a3")
        self.Entry2.configure(font="-family {Consolas} -size 10 -slant italic")
        self.Entry2.configure(foreground="#000000")
        self.Entry2.configure(insertbackground="black")
        self.Entry2.configure(width=174)

        self.Label4 = tk.Label(self.Frame1)
        self.Label4.place(relx=0.099, rely=0.374, height=24, width=62)
        self.Label4.configure(background="#CAFAFE")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(font="-family {Consolas} -size 11 -weight bold -slant italic")
        self.Label4.configure(foreground="#379683")
        self.Label4.configure(text='''Branch:''')
        self.Label4.configure(width=62)

        self.Entry3 = tk.Entry(self.Frame1)
        self.Entry3.place(relx=0.37, rely=0.374,height=20, relwidth=0.43)
        self.Entry3.configure(background="#e0ffff")
        self.Entry3.configure(disabledforeground="#a3a3a3")
        self.Entry3.configure(font="-family {Consolas} -size 10 -slant italic")
        self.Entry3.configure(foreground="#000000")
        self.Entry3.configure(insertbackground="black")
        self.Entry3.configure(width=174)

        self.Label5 = tk.Label(self.Frame1)
        self.Label5.place(relx=0.099, rely=0.486, height=21, width=54)
        self.Label5.configure(background="#CAFAFE")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(font="-family {Consolas} -size 11 -weight bold -slant italic")
        self.Label5.configure(foreground="#379683")
        self.Label5.configure(text='''CGPA:''')
        self.Label5.configure(width=54)

        self.Entry4 = tk.Entry(self.Frame1)
        self.Entry4.place(relx=0.37, rely=0.486,height=20, relwidth=0.43)
        self.Entry4.configure(background="#e0ffff")
        self.Entry4.configure(disabledforeground="#a3a3a3")
        self.Entry4.configure(font="-family {Consolas} -size 10 -slant italic")
        self.Entry4.configure(foreground="#000000")
        self.Entry4.configure(insertbackground="black")
        self.Entry4.configure(width=174)

        self.Label6 = tk.Label(self.Frame1)
        self.Label6.place(relx=0.074, rely=0.598, height=21, width=82)
        self.Label6.configure(background="#CAFAFE")
        self.Label6.configure(disabledforeground="#a3a3a3")
        self.Label6.configure(font="-family {Consolas} -size 11 -weight bold -slant italic")
        self.Label6.configure(foreground="#379683")
        self.Label6.configure(text='''File Name:''')
        self.Label6.configure(width=82)

        self.Entry5 = tk.Entry(self.Frame1)
        self.Entry5.place(relx=0.37, rely=0.598,height=20, relwidth=0.43)
        self.Entry5.configure(background="#e0ffff")
        self.Entry5.configure(disabledforeground="#a3a3a3")
        self.Entry5.configure(font="-family {Consolas} -size 10 -slant italic")
        self.Entry5.configure(foreground="#000000")
        self.Entry5.configure(insertbackground="black")
        self.Entry5.configure(width=174)

        self.Button1 = tk.Button(self.Frame1)
        self.Button1.place(relx=0.321, rely=0.804, height=34, width=127)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#7283d8")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font="-family {Consolas} -size 11 -weight bold -slant italic")
        self.Button1.configure(foreground="#0e2621")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(relief="groove")
        self.Button1.configure(text='''Submit''')
        self.Button1.configure(width=127)
        self.Button1.configure(command=self.clicked1)

        self.Frame2 = tk.Frame(top)
        self.Frame2.place(relx=0.517, rely=0.035, relheight=0.927
                , relwidth=0.463)
        self.Frame2.configure(relief='groove')
        self.Frame2.configure(borderwidth="2")
        self.Frame2.configure(relief="groove")
        self.Frame2.configure(background="#CAFAFE")
        self.Frame2.configure(width=385)

        self.Label7 = tk.Label(self.Frame2)
        self.Label7.place(relx=0.026, rely=0.019, height=41, width=364)
        self.Label7.configure(background="#CAFAFE")
        self.Label7.configure(disabledforeground="#a3a3a3")
        self.Label7.configure(font="-family {Constantia} -size 11 -weight bold -underline 1")
        self.Label7.configure(foreground="#296b5d")
        self.Label7.configure(text='''Click on the button below to insert data in the file''')
        self.Label7.configure(width=364)

        self.Button2 = tk.Button(self.Frame2)
        self.Button2.place(relx=0.338, rely=0.486, height=34, width=137)
        self.Button2.configure(activebackground="#ececec")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#7283d8")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(font="-family {Consolas} -size 11 -weight bold -slant italic")
        self.Button2.configure(foreground="#0e2621")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(relief="groove")
        self.Button2.configure(text='''Click Here!''')
        self.Button2.configure(width=137)
        self.Button2.configure(command=self.clicked2)


    def clicked1(self):
        usn=self.Entry1.get()
        name=self.Entry2.get()
        branch=self.Entry3.get()
        cgpa=self.Entry4.get()
        file=self.Entry5.get()
        
        if usn=="":
            tm.showerror("Error", "Please enter your USN")
        elif name=="":
            tm.showerror("Error", "Please enter your Name")
        elif branch=="":
            tm.showerror("Error", "Please enter your Branch")
        elif cgpa=="":
            tm.showerror("Error", "Please enter your CGPA")
        elif file=="":
            tm.showerror("Error", "Please enter filename")
        else:
            f = open(self.Entry5.get(), 'a')
            line = usn + "|" + name + "|" + branch + "|" + cgpa  + "\n"
            f.write(line)
            f.close()
            tm.showinfo("Create Information", "Data Inserted")

    def clicked2(self):
        # root.destroy()
        os.system('start " " demofile.txt')

if __name__ == '__main__':
    vp_start_gui()





