#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#    May 21, 2019 12:15:23 AM IST  platform: Windows NT

import sys
import tkinter.messagebox as tm
import os

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import insert_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    insert_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    insert_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("832x579+263+62")
        top.title("Insert")
        top.configure(background="#bfeaef")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.254, rely=0.123, relheight=0.712
                , relwidth=0.537)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#CAFAFE")
        self.Frame1.configure(width=445)

        self.Label1 = tk.Label(self.Frame1)
        self.Label1.place(relx=0.247, rely=0.049, height=31, width=224)
        self.Label1.configure(background="#CAFAFE")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Comic Sans MS} -size 11 -weight bold -slant italic -underline 1")
        self.Label1.configure(foreground="#379683")
        self.Label1.configure(text='''Insert''')
        self.Label1.configure(width=224)

        self.Label2 = tk.Label(self.Frame1)
        self.Label2.place(relx=0.09, rely=0.247, height=21, width=134)
        self.Label2.configure(background="#CAFAFE")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font="-family {Consolas} -size 11 -weight bold -slant italic")
        self.Label2.configure(foreground="#379683")
        self.Label2.configure(text='''Enter data file:''')
        self.Label2.configure(width=134)

        self.Entry1 = tk.Entry(self.Frame1)
        self.Entry1.place(relx=0.517, rely=0.247,height=20, relwidth=0.413)
        self.Entry1.configure(background="#e0ffff")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="-family {Consolas} -size 10 -slant italic")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(width=184)

        self.Label3 = tk.Label(self.Frame1)
        self.Label3.place(relx=0.09, rely=0.395, height=21, width=154)
        self.Label3.configure(background="#CAFAFE")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(font="-family {Consolas} -size 11 -weight bold -slant italic")
        self.Label3.configure(foreground="#379683")
        self.Label3.configure(text='''Enter address file:''')
        self.Label3.configure(width=154)

        self.Entry2 = tk.Entry(self.Frame1)
        self.Entry2.place(relx=0.517, rely=0.395,height=20, relwidth=0.413)
        self.Entry2.configure(background="#e0ffff")
        self.Entry2.configure(disabledforeground="#a3a3a3")
        self.Entry2.configure(font="-family {Consolas} -size 10 -slant italic")
        self.Entry2.configure(foreground="#000000")
        self.Entry2.configure(insertbackground="black")
        self.Entry2.configure(width=184)

        self.Button1 = tk.Button(self.Frame1)
        self.Button1.place(relx=0.337, rely=0.593, height=34, width=137)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#919ad8")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font="-family {Consolas} -size 11 -weight bold -slant italic")
        self.Button1.configure(foreground="#0d19a3")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="#000000")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Submit''')
        self.Button1.configure(width=137)
        self.Button1.configure(command=self.clicked)

        self.Button2 = tk.Button(self.Frame1)
        self.Button2.place(relx=0.112, rely=0.815, height=34, width=137)
        self.Button2.configure(activebackground="#ececec")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#edb5bf")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(font="-family {Corbel} -size 11 -weight bold -slant italic")
        self.Button2.configure(foreground="#274931")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''Open data file''')
        self.Button2.configure(width=137)
        self.Button2.configure(command=self.clicked1)

        self.Button2_1 = tk.Button(self.Frame1)
        self.Button2_1.place(relx=0.607, rely=0.815, height=34, width=137)
        self.Button2_1.configure(activebackground="#ececec")
        self.Button2_1.configure(activeforeground="#000000")
        self.Button2_1.configure(background="#edb5bf")
        self.Button2_1.configure(disabledforeground="#a3a3a3")
        self.Button2_1.configure(font="-family {Corbel} -size 11 -weight bold -slant italic")
        self.Button2_1.configure(foreground="#274931")
        self.Button2_1.configure(highlightbackground="#d9d9d9")
        self.Button2_1.configure(highlightcolor="black")
        self.Button2_1.configure(pady="0")
        self.Button2_1.configure(text='''Open address file''')
        self.Button2_1.configure(command=self.clicked2)

    def clicked(self):
        data=self.Entry1.get()
        address=self.Entry2.get()

        if data=="":
            tm.showerror("Error", "Please enter data filename")
        elif address=="":
            tm.showerror("Error", "Please enter address filename")
        else:
            df = open(self.Entry1.get())
            lst = ['none'] * 60
            while True:
                line = df.readline()
                if not line:
                    break
                arr = line.strip().split("|")
                a = int((arr[0])[-3:])
                while (lst[a % 60] != 'none'):
                    a += 1
                lst[a % 60] = line
            af = open(self.Entry2.get(), 'w')
            for i in lst[0:]:
                if i == 'none':
                    af.write('-1\n')
                else:

                    af.write(i)
            af.close()
            df.close()
            tm.showinfo("Insert Information", "Data Inserted")

    def clicked1(self):
        os.system('start " " demofile.txt')
    def clicked2(self):
        os.system('start " " newfile.txt')

if __name__ == '__main__':
    vp_start_gui()





