#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#    May 20, 2019 11:30:42 PM IST  platform: Windows NT

import sys
import os
import tkinter.messagebox as tm

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import option_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    option_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    option_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("832x579+263+62")
        top.title("Options")
        top.configure(background="#bfeaef")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.037, rely=0.049, relheight=0.892
                , relwidth=0.925)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#CAFAFE")
        self.Frame1.configure(width=755)

        self.Label1 = tk.Label(self.Frame1)
        self.Label1.place(relx=0.132, rely=0.073, height=41, width=564)
        self.Label1.configure(background="#c7f5f9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Consolas} -size 14 -weight bold -slant italic -underline 1")
        self.Label1.configure(foreground="#296b5d")
        self.Label1.configure(text='''Click on the below button to select the option''')
        self.Label1.configure(width=564)

        self.Button1 = tk.Button(self.Frame1)
        self.Button1.place(relx=0.146, rely=0.239, height=44, width=187)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#f4e4c1")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font="-family {Comic Sans MS} -size 11 -weight bold -slant italic")
        self.Button1.configure(foreground="#0d19a3")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Create''')
        self.Button1.configure(width=187)
        self.Button1.configure(command=self.clicked1)

        self.Button1_1 = tk.Button(self.Frame1)
        self.Button1_1.place(relx=0.623, rely=0.239, height=44, width=187)
        self.Button1_1.configure(activebackground="#ececec")
        self.Button1_1.configure(activeforeground="#000000")
        self.Button1_1.configure(background="#edb5bf")
        self.Button1_1.configure(disabledforeground="#a3a3a3")
        self.Button1_1.configure(font="-family {Comic Sans MS} -size 11 -weight bold -slant italic")
        self.Button1_1.configure(foreground="#0d19a3")
        self.Button1_1.configure(highlightbackground="#d9d9d9")
        self.Button1_1.configure(highlightcolor="black")
        self.Button1_1.configure(pady="0")
        self.Button1_1.configure(text='''Insert''')
        self.Button1_1.configure(command=self.clicked2)

        self.Button1_2 = tk.Button(self.Frame1)
        self.Button1_2.place(relx=0.159, rely=0.532, height=44, width=187)
        self.Button1_2.configure(activebackground="#ececec")
        self.Button1_2.configure(activeforeground="#000000")
        self.Button1_2.configure(background="#d3e3fc")
        self.Button1_2.configure(disabledforeground="#a3a3a3")
        self.Button1_2.configure(font="-family {Comic Sans MS} -size 11 -weight bold -slant italic")
        self.Button1_2.configure(foreground="#0d19a3")
        self.Button1_2.configure(highlightbackground="#d9d9d9")
        self.Button1_2.configure(highlightcolor="black")
        self.Button1_2.configure(pady="0")
        self.Button1_2.configure(text='''Search''')
        self.Button1_2.configure(command=self.clicked3)

        self.Button1_3 = tk.Button(self.Frame1)
        self.Button1_3.place(relx=0.623, rely=0.514, height=44, width=187)
        self.Button1_3.configure(activebackground="#ececec")
        self.Button1_3.configure(activeforeground="#000000")
        self.Button1_3.configure(background="#ffffff")
        self.Button1_3.configure(disabledforeground="#a3a3a3")
        self.Button1_3.configure(font="-family {Comic Sans MS} -size 11 -weight bold -slant italic")
        self.Button1_3.configure(foreground="#0d19a3")
        self.Button1_3.configure(highlightbackground="#d9d9d9")
        self.Button1_3.configure(highlightcolor="black")
        self.Button1_3.configure(pady="0")
        self.Button1_3.configure(text='''Delete''')
        self.Button1_3.configure(command=self.clicked4)

        self.Button1_4 = tk.Button(self.Frame1)
        self.Button1_4.place(relx=0.397, rely=0.771, height=44, width=187)
        self.Button1_4.configure(activebackground="#ececec")
        self.Button1_4.configure(activeforeground="#000000")
        self.Button1_4.configure(background="#f76c6c")
        self.Button1_4.configure(disabledforeground="#a3a3a3")
        self.Button1_4.configure(font="-family {Comic Sans MS} -size 11 -weight bold -slant italic")
        self.Button1_4.configure(foreground="#0d19a3")
        self.Button1_4.configure(highlightbackground="#d9d9d9")
        self.Button1_4.configure(highlightcolor="black")
        self.Button1_4.configure(pady="0")
        self.Button1_4.configure(text='''Exit''')
        self.Button1_4.configure(command=self.clicked5)

    def clicked1(self):
        os.system('python create.py')
    def clicked2(self):
        os.system('python insert.py')
    def clicked3(self):
        os.system('python search.py')
    def clicked4(self):
        os.system('python delete.py')
    def clicked5(self):
        if tm.askokcancel("Quit", "Are you sure you want to Exit?"):
            root.destroy()

if __name__ == '__main__':
    vp_start_gui()





