#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#    May 21, 2019 03:40:50 PM IST  platform: Windows NT

import sys
import os 
import tkinter.messagebox as tm
import re
import hashlib 
try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import register_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    register_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    register_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("832x579+263+62")
        top.title("Registration")
        top.configure(background="#bfeaef")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.278, rely=0.068, relheight=0.857
                , relwidth=0.502)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#CAFAFE")
        self.Frame1.configure(width=415)

        self.Label1 = tk.Label(self.Frame1)
        self.Label1.place(relx=0.241, rely=0.02, height=31, width=204)
        self.Label1.configure(background="#CAFAFE")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Old English Text MT} -size 14 -weight bold -slant italic -underline 1")
        self.Label1.configure(foreground="#379683")
        self.Label1.configure(text='''Registration''')
        self.Label1.configure(width=204)

        self.Label2 = tk.Label(self.Frame1)
        self.Label2.place(relx=0.096, rely=0.158, height=21, width=104)
        self.Label2.configure(background="#CAFAFE")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font="-family {Consolas} -size 11 -weight bold -slant italic")
        self.Label2.configure(foreground="#379683")
        self.Label2.configure(text='''Username:''')
        self.Label2.configure(width=104)

        self.Entry1 = tk.Entry(self.Frame1)
        self.Entry1.place(relx=0.482, rely=0.158,height=20, relwidth=0.419)
        self.Entry1.configure(background="#e0ffff")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="-family {Consolas} -size 10 -weight bold -slant italic")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(width=174)

        self.Label3 = tk.Label(self.Frame1)
        self.Label3.place(relx=0.096, rely=0.257, height=21, width=104)
        self.Label3.configure(background="#CAFAFE")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(font="-family {Consolas} -size 12 -weight bold -slant italic")
        self.Label3.configure(foreground="#379683")
        self.Label3.configure(text='''Password:''')
        self.Label3.configure(width=104)

        self.Entry2 = tk.Entry(self.Frame1)
        self.Entry2.place(relx=0.482, rely=0.257,height=20, relwidth=0.419)
        self.Entry2.configure(background="#e0ffff")
        self.Entry2.configure(disabledforeground="#a3a3a3")
        self.Entry2.configure(font="-family {Consolas} -size 10 -weight bold -slant italic")
        self.Entry2.configure(foreground="#000000")
        self.Entry2.configure(insertbackground="black")
        self.Entry2.configure(width=174)
        self.Entry2.configure(show='*')

        self.Label4 = tk.Label(self.Frame1)
        self.Label4.place(relx=0.048, rely=0.356, height=21, width=154)
        self.Label4.configure(background="#CAFAFE")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(font="-family {Consolas} -size 12 -weight bold -slant italic")
        self.Label4.configure(foreground="#379683")
        self.Label4.configure(text='''Confirm Password:''')
        self.Label4.configure(width=154)

        self.Entry3 = tk.Entry(self.Frame1)
        self.Entry3.place(relx=0.482, rely=0.356,height=20, relwidth=0.419)
        self.Entry3.configure(background="#e0ffff")
        self.Entry3.configure(disabledforeground="#a3a3a3")
        self.Entry3.configure(font="-family {Consolas} -size 10 -weight bold -slant italic")
        self.Entry3.configure(foreground="#000000")
        self.Entry3.configure(insertbackground="black")
        self.Entry3.configure(width=174)
        self.Entry3.configure(show='*')

        self.Label5 = tk.Label(self.Frame1)
        self.Label5.place(relx=0.096, rely=0.455, height=21, width=104)
        self.Label5.configure(background="#CAFAFE")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(font="-family {Consolas} -size 12 -weight bold -slant italic")
        self.Label5.configure(foreground="#379683")
        self.Label5.configure(text='''Email:''')
        self.Label5.configure(width=104)

        self.Entry4 = tk.Entry(self.Frame1)
        self.Entry4.place(relx=0.482, rely=0.455,height=20, relwidth=0.419)
        self.Entry4.configure(background="#e0ffff")
        self.Entry4.configure(disabledforeground="#a3a3a3")
        self.Entry4.configure(font="-family {Consolas} -size 10 -weight bold -slant italic")
        self.Entry4.configure(foreground="#000000")
        self.Entry4.configure(insertbackground="black")
        self.Entry4.configure(width=174)

        self.Label6 = tk.Label(self.Frame1)
        self.Label6.place(relx=0.096, rely=0.554, height=21, width=114)
        self.Label6.configure(background="#CAFAFE")
        self.Label6.configure(disabledforeground="#a3a3a3")
        self.Label6.configure(font="-family {Consolas} -size 12 -weight bold -slant italic")
        self.Label6.configure(foreground="#379683")
        self.Label6.configure(text='''Phone No.''')
        self.Label6.configure(width=114)

        self.Entry5 = tk.Entry(self.Frame1)
        self.Entry5.place(relx=0.482, rely=0.554,height=20, relwidth=0.419)
        self.Entry5.configure(background="#e0ffff")
        self.Entry5.configure(disabledforeground="#a3a3a3")
        self.Entry5.configure(font="-family {Consolas} -size 10 -weight bold -slant italic")
        self.Entry5.configure(foreground="#000000")
        self.Entry5.configure(insertbackground="black")
        self.Entry5.configure(width=174)

        self.Label7 = tk.Label(self.Frame1)
        self.Label7.place(relx=0.096, rely=0.653, height=21, width=104)
        self.Label7.configure(background="#CAFAFE")
        self.Label7.configure(disabledforeground="#a3a3a3")
        self.Label7.configure(font="-family {Consolas} -size 12 -weight bold -slant italic")
        self.Label7.configure(foreground="#379683")
        self.Label7.configure(text='''Address:''')
        self.Label7.configure(width=104)

        self.Entry6 = tk.Entry(self.Frame1)
        self.Entry6.place(relx=0.482, rely=0.653,height=50, relwidth=0.419)
        self.Entry6.configure(background="#e0ffff")
        self.Entry6.configure(disabledforeground="#a3a3a3")
        self.Entry6.configure(font="-family {Consolas} -size 10 -weight bold -slant italic")
        self.Entry6.configure(foreground="#000000")
        self.Entry6.configure(insertbackground="black")
        self.Entry6.configure(width=174)

        self.Button1 = tk.Button(self.Frame1)
        self.Button1.place(relx=0.241, rely=0.851, height=34, width=77)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#edb5bf")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font="-family {Rockwell} -size 12 -weight bold -slant italic")
        self.Button1.configure(foreground="#379683")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Signup''')
        self.Button1.configure(width=77)
        self.Button1.configure(command=self.clicked1)

        self.Button1_1 = tk.Button(self.Frame1)
        self.Button1_1.place(relx=0.578, rely=0.851, height=34, width=77)
        self.Button1_1.configure(activebackground="#ececec")
        self.Button1_1.configure(activeforeground="#000000")
        self.Button1_1.configure(background="#f76c6c")
        self.Button1_1.configure(disabledforeground="#a3a3a3")
        self.Button1_1.configure(font="-family {Rockwell} -size 12 -weight bold -slant italic")
        self.Button1_1.configure(foreground="#2a7264")
        self.Button1_1.configure(highlightbackground="#d9d9d9")
        self.Button1_1.configure(highlightcolor="black")
        self.Button1_1.configure(pady="0")
        self.Button1_1.configure(text='''Login''')
        self.Button1_1.configure(command=self.clicked2)

    def clicked2(self):
        root.destroy()
        os.system('python login.py')
    def clicked1(self):
        name=self.Entry1.get()
        pwd=self.Entry2.get()
        cpwd=self.Entry3.get()
        email=self.Entry4.get()
        phone=self.Entry5.get()
        add=self.Entry6.get()


        def isValid(phone): 
             
            Pattern = re.compile("(0/91)?[7-9][0-9]{9}") 
            return Pattern.match(phone)

        addressToVerify = email
        match = re.match('^[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,4})$', addressToVerify)

        

        if name=="":
            tm.showerror("Error", "Please enter your name")
        elif pwd=="":
            tm.showerror("Error", "Please enter password")
        
        elif (len(pwd)<8): 
            tm.showerror("Error", "Please enter correct password")
        elif not re.search("[A-Z]", pwd): 
            tm.showerror("Error", "Please enter correct password")
        elif not re.search("[a-z]", pwd): 
            tm.showerror("Error", "Please enter correct password")
        elif not re.search("[0-9]", pwd): 
            tm.showerror("Error", "Please enter correct password")
        elif not re.search("[_@$]", pwd): 
            tm.showerror("Error", "Please enter correct password")
        
        elif cpwd=="":
            tm.showerror("Error", "Please enter confirm password")
        elif pwd!=cpwd:
            tm.showerror("Error", "Password did not match")
        elif email=="":
            tm.showerror("Error", "Please enter your email")
        elif match == None:
            tm.showerror("Error","Invalid Email-Id") 
        elif phone=="":
            tm.showerror("Error", "Please enter phone no")
        elif  not isValid(phone): 
            tm.showerror("Error","Invalid Phone number")    
        elif add=="":
            tm.showerror("Error", "Please enter address")  
        
        else:
            result = hashlib.sha256(pwd.encode())
            pwd1=result.hexdigest()
            f = open('login.txt', 'a')
            line = name + "|" + pwd1 + "|" + email + "|" + phone + "|" + add + "\n"
            f.write(line)
            f.close()
            tm.showinfo("Registration Information", "Registration Successfull")
            root.destroy()
            os.system('python login.py')

if __name__ == '__main__':
    vp_start_gui()





